### ISSUE TITLE
Error updating Cloudflare ranges

### ISSUE THREAD

**Issue by syrinxtech** [oldrho/ip2provider#8]
When I use the `--update-lists` option, I get the following error:

```
Traceback (most recent call last):
  File "/home/kali/tools/OSINT/ip2provider/./ip2provider.py", line 201, in <module>
    main()
  File "/home/kali/tools/OSINT/ip2provider/./ip2provider.py", line 58, in main
    update()
  File "/home/kali/tools/OSINT/ip2provider/./ip2provider.py", line 195, in update
    total += cloudflare.update()
             ^^^^^^^^^^^^^^^^^^^
  File "/home/kali/tools/OSINT/ip2provider/lists/cloudflare.py", line 17, in update
    elements = soup.find('h2',string='IPv4').parent.find_all('li')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'parent'
```

I went to the URL shown in the _cloudflare.py_ file and it did provide a text file listing.  Any thoughts?

**Comment by oldrho** [comment]
Fixed as of 598d637 - also support IPv6 from Cloudflare now.
